services:
    app:
        build:
            context: 'docker/php-cli'
            args:
                APP_UID: '${UID}'
                APP_GID: '${GID}'
        environment:
            COMPOSER_AUTH: '${COMPOSER_AUTH:-}'
            DB_HOST: 'db'
        extra_hosts:
            - 'host.docker.internal:host-gateway' # Matches xdebug.client_host
        depends_on:
            - 'db'
        volumes:
            - '.:/app:rw,cached'
            - 'composer:/home/www/.composer'

    db:
        image: 'mariadb:11.8'
        ports:
            - 3306
        environment:
            MARIADB_ROOT_PASSWORD: '!root'
            MARIADB_DATABASE: 'tests'
            MARIADB_USER: 'tests'
            MARIADB_PASSWORD: 'tests'
        volumes:
            - 'db-data:/var/lib/mysql'
            - './docker/db-data:/docker-entrypoint-initdb.d'

volumes:
    composer:
    db-data:
