services:
    app:
        build:
            context: 'docker/php-cli'
            args:
                APP_UID: '${UID}'
                APP_GID: '${GID}'
        environment:
            COMPOSER_AUTH: '${COMPOSER_AUTH:-}'
            DB_HOST: 'db'
        depends_on:
            - 'db'
        volumes:
            - '.:/var/www/html:rw,cached'
            - 'composer:/home/www/.composer'

    db:
        image: 'mariadb:10.6'
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: '!root'
            MYSQL_DATABASE: 'tests'
            MYSQL_USER: 'tests'
            MYSQL_PASSWORD: 'tests'
        volumes:
            - 'db-data:/var/lib/mysql'
            - './docker/db-data:/docker-entrypoint-initdb.d'

volumes:
    composer:
    db-data:
