name: 'Static Analysis'

on:
    pull_request: ~
    push:
        branches:
            - 'main'

jobs:
    static-analysis:
        runs-on: 'ubuntu-latest'

        steps:
            - name: 'Checkout'
              uses: 'actions/checkout@v3'

            - name: 'Install PHP'
              uses: 'shivammathur/setup-php@v2'
              with:
                  php-version: '8.1'
                  coverage: 'none'
                  extensions: 'mbstring'
                  tools: 'composer:v2'

            - name: 'Get composer cache directory'
              id: 'composer-cache'
              run: 'echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT'

            - name: 'Cache dependencies'
              uses: 'actions/cache@v3'
              with:
                  path: '${{ steps.composer-cache.outputs.dir }}'
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: '${{ runner.os }}-composer-'

            - name: 'Install dependencies'
              run: 'composer install --prefer-dist'

            - name: 'Run composer audit'
              run: 'composer audit --format=plain'

            - name: 'Run PHP Parallel Lint'
              run: 'vendor/bin/parallel-lint app bin src tests'

            - name: 'Run PHP CodeSniffer'
              run: 'vendor/bin/phpcs'

            - name: 'Run PHPStan'
              run: 'vendor/bin/phpstan analyse'
